### PR TITLE
Moved to actions, documented with doxygen

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by evaherrada** [comment]
@ladyada Should this only be tested with a few boards since it's the 'tiny' library?

**Comment by ladyada** [comment]
yah this is for trinket/gemma attiny85's only!

**Comment by evaherrada** [comment]
@ladyada Is that the case for every 'tiny' library?

**Comment by ladyada** [comment]
*probably*

**Comment by PaintYourDragon** [comment]
Usually but not always. Like…Adafruit_TinyFlash was written with ATtiny in mind, but should also work on AVRs and probably others. Consider it a hint but not a rule.

**Review by PaintYourDragon — APPROVED** [review]

**Pull request merged**
